platform :ios 
pod 'JSONKit', '~> 1.5pre'
pod 'Masonry', '~> 0.6.1'
pod 'JDStatusBarNotification', '~> 1.5.1'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'ODRefreshControl', '~> 1.1.0'
pod 'SMPageControl', '~> 1.2'
pod 'MBProgressHUD', '~> 0.9.1'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.2'